// Alle vragen en antwoorden komen uit de teksten op manegehooidonk.nl (stand 05-10-2026).
// Bij manege-vragen is "uitleg" (bijna) letterlijk van de site; "bron" is de pagina.

const MANEGE_VRAGEN = [
  { e: "📍", v: "In welke plaats ligt Manege Hooidonk?", goed: "Nuenen", fout: ["Eindhoven", "Geldrop", "Helmond"], uitleg: "Manege Hooidonk, Beekstraat 48, 5673 NA Nuenen. De manege ligt tegen een bosrijke omgeving, waarin mooie buitenritten te maken zijn.", bron: "contact" },
  { e: "⭐", v: "Hoeveel sterren heeft Manege Hooidonk?", goed: "4 sterren", fout: ["2 sterren", "3 sterren", "5 sterren"], uitleg: "Op de homepage prijken vier gouden sterren. Manege Hooidonk is een gastvrije FNRS/KNHS-manege.", bron: "homepage" },
  { e: "🤖", v: "Hoe heet het mechanische paard van de manege?", goed: "Ronnie", fout: ["Robbie", "Rocky", "Ricky"], uitleg: "Volwassen beginners krijgen o.a. 2 lessen op ons mechanisch paard Joker Ronnie.", bron: "lessen" },
  { e: "🧒", v: "Hoe oud zijn de kinderen in de kabouterles?", goed: "6 en 7 jaar", fout: ["3 en 4 jaar", "10 en 11 jaar", "13 tot 19 jaar"], uitleg: "Voor de jongere kinderen van 6-7 jaar zijn er kabouterlessen. Op een speelse wijze leren ze de beginselen van het ponyrijden. Plezier staat voorop!", bron: "lessen" },
  { e: "🐴", v: "Voor welke leeftijd is de beginnersles pony bedoeld?", goed: "8 tot 12 jaar", fout: ["4 tot 6 jaar", "13 tot 19 jaar", "Alleen volwassenen"], uitleg: "De beginnersles pony is speciaal bedoeld voor 8-12 jarigen die nog niet of nauwelijks gereden hebben. Vooraf leer je je pony poetsen en opzadelen en daarna rijd je een uur.", bron: "lessen" },
  { e: "📏", v: "Tot welke stokmaat noemen ze het een pony?", goed: "147 cm", fout: ["120 cm", "135 cm", "160 cm"], uitleg: "Pony is t/m stokmaat 147 cm. Paard is na stokmaat 147 cm.", bron: "prijslijst" },
  { e: "⛑️", v: "Welk keurmerk moet er op een goede cap zitten?", goed: "CE-EN 1384", fout: ["KNHS-147", "CE-EN 2026", "FNRS-4"], uitleg: "Het belangrijkste is dat er een veiligheidskeurmerk op zit. Dit moet het CE-EN 1384 keurmerk zijn, zodat je zeker weet dat je een goede, veilige cap op je hoofd hebt.", bron: "wat heb ik nodig" },
  { e: "🙆", v: "Hoe test je of je cap goed zit?", goed: "Hem vastmaken en heel hard 'ja' knikken", fout: ["Hard 'nee' schudden", "Op en neer springen", "Erop kloppen"], uitleg: "Maak hem vast en ga eventjes heel hard knikken alsof je ja knikt. Schuift de cap van je hoofd af, dan zit hij te los. Voel je hem knellen, dan mag hij wat losser.", bron: "wat heb ik nodig" },
  { e: "🧥", v: "Waarom is een hoodie met capuchon niet veilig bij het paardrijden?", goed: "Je kunt bij een val ergens achter blijven haken", fout: ["Het paard schrikt van de capuchon", "Je krijgt het veel te warm", "Je cap past er dan niet op"], uitleg: "Een capuchon/hoodie is niet veilig: hiermee kun je bij een val ergens achter blijven haken. Rijd om deze reden ook nooit met je jas of vest open.", bron: "wat heb ik nodig" },
  { e: "💇", v: "Hoe doe je lang haar het beste tijdens het paardrijden?", goed: "In een lage staart", fout: ["In een hoge staart", "Lekker los", "In een knot bovenop je hoofd"], uitleg: "Bind je haar vast in een lage staart. Een hoge staart kan knel komen te zitten tussen je hoofd en de cap. Er zijn ook speciale haarnetjes.", bron: "wat heb ik nodig" },
  { e: "🧤", v: "Welke kleur handschoenen draag je op een wedstrijd?", goed: "Wit", fout: ["Zwart", "Roze", "Rood"], uitleg: "Wil je tijdens je wedstrijden handschoenen dragen? Draag dan witte handschoenen, zodat de jury kan zien wat je doet.", bron: "wat heb ik nodig" },
  { e: "👖", v: "Waarom is een spijkerbroek niet zo handig om in te rijden?", goed: "De dikke naden aan de binnenkant kunnen schuren", fout: ["Het paard vindt blauw eng", "Hij is te glad voor het zadel", "Hij gaat stuk van het zweet"], uitleg: "Pas op met dikke naden aan de binnenkant zoals bij spijkerbroeken, die kunnen gaan schuren. Een rijbroek is elastisch en beweegt goed mee.", bron: "wat heb ik nodig" },
  { e: "👢", v: "Wat zijn 'chaps'?", goed: "Leren of suède stukken om je kuit, met een rits", fout: ["Speciale paardensnoepjes", "Kleine zadeltasjes", "Sokken voor in je laarzen"], uitleg: "Chaps zijn leren of suède stukken die je om je kuit heen vast kunt maken met een rits. Ze beschermen je kuiten net zoals rijlaarzen dat doen.", bron: "wat heb ik nodig" },
  { e: "🪩", v: "Wanneer is er Disco Ponyrijden?", goed: "Iedere laatste vrijdag van de maand", fout: ["Elke zondagochtend", "Iedere eerste zaterdag", "Alleen met carnaval"], uitleg: "Disco Ponyrijden: iedere laatste vrijdag van de maand, € 20,00 per keer. Voor iedereen die stap, draf en galop goed beheerst.", bron: "nieuws" },
  { e: "👶", v: "Op welke dag is 'Ponyrijden voor de allerkleinsten'?", goed: "Zondag", fout: ["Maandag", "Woensdag", "Vrijdag"], uitleg: "Op zondagen om 10.30 uur kunnen de allerjongsten komen ponyrijden, ook in de zomervakantie. Eerst poetsen, dan een half uur rijden.", bron: "allerkleinsten" },
  { e: "👨‍👧", v: "Wie loopt er mee bij 'Ponyrijden voor de allerkleinsten'?", goed: "Een ouder of begeleider", fout: ["Een andere pony", "Niemand", "De hoefsmid"], uitleg: "Een ouder en/of begeleider moet in de rijbaan/het bos assisteren om de kinderen te ondersteunen.", bron: "allerkleinsten" },
  { e: "🌡️", v: "Vanaf hoeveel graden gaan de lessen niet door?", goed: "36 graden", fout: ["26 graden", "30 graden", "40 graden"], uitleg: "Hitteprotocol: tot 26° normaal, 27-30° aangepast, 31-35° buitenritten onder de bomen, vanaf 36° worden lessen geannuleerd. Het welzijn van de paarden is topprioriteit!", bron: "hitteprotocol" },
  { e: "💦", v: "Wat doen de paarden het laatste kwartier van de les als het 27 tot 30 graden is?", goed: "Afkoelen onder de sproeiers", fout: ["Een ijsje eten", "Zwemmen in het ven", "Slapen in de stal"], uitleg: "Bij warm weer gaan ze het laatste kwartier onder de sproeiers in de buitenbak om af te koelen, en er zijn extra stapmomenten in de les.", bron: "hitteprotocol" },
  { e: "🌳", v: "Waar gaan de ritten heen als het 31 tot 35 graden is?", goed: "Buitenritten onder de bomen", fout: ["Naar het strand", "Alleen in de binnenbak", "Rondjes over de parkeerplaats"], uitleg: "Bij 31 tot 35 graden zijn het buitenritten onder de bomen: veel stap en een beetje draf.", bron: "hitteprotocol" },
  { e: "🐎", v: "Hoeveel shetlanders wonen er op de manege?", goed: "6", fout: ["2", "4", "10"], uitleg: "Er zijn Erica, Laurey, Brammetje, Ushi, Tutti en Twinkel. Zij wonen samen in een paddock met 2 grote loopstallen.", bron: "foto's pony's" },
  { e: "✨", v: "Welke van deze namen is een shetlander van de manege?", goed: "Twinkel", fout: ["Pluisje", "Snoopy", "Bolletje"], uitleg: "De shetlanders heten Erica, Laurey, Brammetje, Ushi, Tutti en Twinkel. Ze doen mee bij kinderfeestjes, ponydagen en ponykampen.", bron: "foto's pony's" },
  { e: "🎂", v: "Hoe heet het kinderfeestje op de manege?", goed: "Pimp & Ride", fout: ["Pony Party", "Ride & Shine", "Paardenpret"], uitleg: "Bij het kinderfeestje 'Pimp & Ride' ga je met je vrienden twee shetlanders poetsen en versieren, cake versieren en ponyrijden.", bron: "kinderfeestje" },
  { e: "🎀", v: "Wat doe je bij 'Pimp my pony' op het kinderfeestje?", goed: "Twee shetlanders poetsen en versieren", fout: ["Een pony verven", "Een pony-schilderij maken", "Een paardentrailer versieren"], uitleg: "Na de ontvangst ga je naar de poetsplaats, waar je met je vrienden/vriendinnen twee shetlanders gaat poetsen en versieren.", bron: "kinderfeestje" },
  { e: "🌭", v: "Wat eet je na het ponyrijden op het kinderfeestje?", goed: "Een broodje knakworst", fout: ["Pannenkoeken", "Pizza", "Patat"], uitleg: "Na het ponyrijden is er voor iedereen een broodje kipknakworstjes of vegetarische knakworstjes. In de pauze mag je ook een plak cake versieren met snoep.", bron: "kinderfeestje" },
  { e: "🍰", v: "Waarmee mag je de cake versieren op het kinderfeestje?", goed: "Met eetbaar snoep", fout: ["Met hooi", "Met wortels", "Met glitter"], uitleg: "Pauze met drinken. Ook krijg je een plak cake, die je mag versieren met eetbaar snoep.", bron: "kinderfeestje" },
  { e: "⛺", v: "Waar slapen de kinderen tijdens het ponykamp?", goed: "Op 'Camping Hooidonk' in een rijhal", fout: ["In het hooi bij de pony's", "In een hotel", "In het bos onder de sterren"], uitleg: "In één van de rijhallen wordt 'Camping Hooidonk' ingericht met privé tenten, zwembad en een zithoek in het thema van het kamp. Ook de leiding slaapt daar.", bron: "ponykampen" },
  { e: "🎭", v: "Waarmee eindigt de kampweek?", goed: "Met een optreden voor de ouders", fout: ["Met vuurwerk", "Met een paardenrace", "Met een disco"], uitleg: "De kampweek wordt afgesloten met een optreden voor de ouders en andere geïnteresseerden.", bron: "ponykampen" },
  { e: "🧑‍🎤", v: "Voor welke leeftijd is het tienerkamp?", goed: "13 tot en met 19 jaar", fout: ["8 tot 12 jaar", "6 en 7 jaar", "20 jaar en ouder"], uitleg: "Het tienerkamp is voor 13 t/m 19 jarigen. Rijervaring is een vereiste: er is o.a. een dressuurwedstrijd, avondrit, dagtocht, spring- en dressuurles.", bron: "ponykampen" },
  { e: "🍂", v: "Wanneer zijn de ponydagen in de herfstvakantie 2026?", goed: "19 t/m 23 oktober", fout: ["5 t/m 9 oktober", "26 t/m 30 oktober", "2 t/m 6 november"], uitleg: "Ponydagen herfstvakantie: 19 t/m 23 oktober 2026. Een dag vol ponyrijden en spelletjes met pony's, lunch inbegrepen.", bron: "ponydagen" },
  { e: "🕘", v: "Hoe laat begint het programma van een ponydag?", goed: "9.00 uur", fout: ["7.00 uur", "11.00 uur", "13.00 uur"], uitleg: "Het ponydagen-programma start om 9.00u en eindigt om 17.00u. Brengen kan tussen 8.00 en 9.00 uur.", bron: "ponydagen" },
  { e: "🎄", v: "Hoe heet het feest op 20 december 2026?", goed: "Kerst op Stal", fout: ["Pony-kerstmarkt", "Winterrit", "Sneeuwdisco"], uitleg: "Op de activiteitenkalender: 20 december 2026 Kerst op Stal.", bron: "activiteitenkalender" },
  { e: "🌷", v: "Wanneer is de Open Paardendag?", goed: "23 mei 2027", fout: ["1 januari 2027", "27 april 2027", "31 oktober 2026"], uitleg: "Op de activiteitenkalender: 23 mei 2027 Open Paardendag.", bron: "activiteitenkalender" },
  { e: "📱", v: "Met welke app boek je lessen en zeg je af?", goed: "Manegeplan", fout: ["PonyApp", "Paardenplan", "RuiterWeb"], uitleg: "Via de app Manegeplan heb je toegang tot je afspraken. Je kunt er afzeggen, inhaallessen boeken en je inschrijven voor wedstrijden en buitenritten.", bron: "klantenportaal" },
  { e: "⏰", v: "Hoe lang van tevoren moet je een les afzeggen?", goed: "24 uur", fout: ["1 uur", "1 week", "1 maand"], uitleg: "Meld je tijdig af (24 uur vooraf) via het klantenportaal. Met een lopend abonnement kun je de les dan een jaar lang inhalen.", bron: "lessen" },
  { e: "🏆", v: "Bij welke branchevereniging is de manege aangesloten?", goed: "FNRS", fout: ["KNVB", "ANWB", "FNV"], uitleg: "De manege is lid van de FNRS. Daardoor voldoet ze aan eisen voor kwaliteit, veiligheid en welzijn van mens en paard.", bron: "kwaliteit" },
  { e: "🟠", v: "Welke kleuren heeft het bord van de Stichting Veilige Paardensport?", goed: "Oranje-wit", fout: ["Blauw-geel", "Rood-zwart", "Groen-wit"], uitleg: "Het bewijs voor de veiligheid herken je aan het blauwe FNRS-bord en het oranje-witte bord van de Stichting Veilige Paardensport.", bron: "kwaliteit" },
  { e: "🌿", v: "Waar letten ze op bij het welzijn van de paarden?", goed: "Voer, gezondheid, stalklimaat en buitenstaan", fout: ["Alleen hoe mooi ze zijn", "Hoe snel ze kunnen rennen", "Hoeveel prijzen ze winnen"], uitleg: "Bij de keuring wordt gekeken naar voermanagement, de gezondheid van de paarden, het stalklimaat, contact met andere paarden, buitenstaan en vrije beweging.", bron: "kwaliteit" },
  { e: "🌲", v: "Hoe lang duurt een buitenrit in de groep?", goed: "2 uur", fout: ["15 minuten", "1 uur", "Een hele dag"], uitleg: "Op de prijslijst: Buitenrit 2 uurs in groep.", bron: "prijslijst" },
  { e: "🗓️", v: "Hoeveel dagen per week rijd je met het Excellent-abonnement?", goed: "3 dagen", fout: ["1 dag", "5 dagen", "Elke dag"], uitleg: "Met het Excellent Maandabonnement rijd je 3 dagen per week met een vast paard of een vaste pony: 'het gevoel van een eigen paard'.", bron: "lessen" },
];

// Pony-trivia: het antwoord is een pony uit PONYS; "niet" = namen die ook zouden kunnen kloppen en dus geen fout antwoord mogen zijn.
const PONY_VRAGEN = [
  { v: "Wie is het oudste paard van de manege?", a: "Paraguay", hint: "Zij is geboren op 12-02-1988!" },
  { v: "Wie is het grootste paard van de manege?", a: "Legend" },
  { v: "Wie is een Friese hengst?", a: "Holbe" },
  { v: "Wie gaat op buitenrit het liefst zwemmen in het water?", a: "Stardust" },
  { v: "Wie is de beste vriendin van Stardust?", a: "Tilly" },
  { v: "Wie is de beste vriend van Freckles?", a: "Sky" },
  { v: "Dino speelt het liefst met Jack en ...?", a: "Vulcan", niet: ["Henk"] },
  { v: "Wie speelt in de paddock met Jack en Dino?", a: "Henk", niet: ["Vulcan"] },
  { v: "Wie is de beste vriendin van Daffia?", a: "Biolga" },
  { v: "Wie is de beste vriend van Noeska?", a: "Denoah" },
  { v: "Wie heeft een maatje aan Boris?", a: "Elton" },
  { v: "Wie heeft een veulen dat Yalou heet?", a: "Beertje Balou" },
  { v: "Wie zou in maart-april 2026 een veulen krijgen?", a: "Abria B" },
  { v: "Wie heeft in de Prix St. George gelopen?", a: "Banner Man S" },
  { v: "Wie wordt een 'wolf in schaapskleren' genoemd?", a: "Jack" },
  { v: "Wie snoept op buitenrit graag van het gras en de boompjes?", a: "Llinos" },
  { v: "Wie is een haflinger die alles doet voor eten?", a: "Cassandra", niet: ["Betty Boop"] },
  { v: "Wie houdt het hoofd grappig hoog als je het hoofdstel omdoet?", a: "Foramé" },
  { v: "Met wie rijdt instructeur Kyra in het viertal Kür op Muziek?", a: "Haut Brion" },
  { v: "Wie snapt helemaal niets van hindernissen?", a: "Legend" },
  { v: "Wie is een lieve connemara ruin?", a: "Paddy" },
  { v: "Wie is een jonge Arabische merrie?", a: "Pippie" },
  { v: "Wie is soms een 'grumpy old man' op stal?", a: "Collin", niet: ["Harley"] },
  { v: "Wie geeft altijd 110% aan zijn ruiters?", a: "Dino" },
  { v: "Wie is de grote favoriet bij de F-proeven?", a: "Vulcan" },
  { v: "Wie is 'een echte turbo onder de paarden'?", a: "Glennfeddich" },
  { v: "Wie is een echt poppetje en heeft het liefst de kleinste kinderen in de stal?", a: "China Doll" },
  { v: "Wie heeft een zilveren kleur met stippen?", a: "Popcorn Hidalgo" },
  { v: "Wie heeft op buitenrit altijd de oortjes vooruit?", a: "Desperado" },
  { v: "Wie probeert je uit door hoeken af te snijden en langzaam te gaan?", a: "Estherette" },
  { v: "Wie lost in het parcours de fouten van zijn ruiter op?", a: "Conner Z" },
  { v: "Wie geniet ervan als ze mooie vlechten in haar manen krijgt?", a: "Bontje", niet: ["Holbe"] },
  { v: "Wie houdt van lekker kriebelen bij zijn oren?", a: "Browny" },
  { v: "Wie loopt mee in het Z-viertal Kür op muziek?", a: "First Impression", niet: ["Haut Brion", "Aduria"] },
  { v: "Wie gaat graag mee voorop op een buitenrit?", a: "Slechtweervandaag", niet: ["Annemarie", "Cupido Z"] },
  { v: "Wie wil haar grenzen nog wel eens opzoeken?", a: "Peanut" },
];
